# ==============================
# PersistentVolumeClaim
# ==============================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
  namespace: clarence
spec:
  accessModes:
    - ReadWriteOnce  # 单节点读写
  resources:
    requests:
      storage: 1Gi  # 请求 1GB 存储空间
  storageClassName: alicloud-disk-immediate-v2  # 阿里云高效云盘

